# Generated by Django 4.2 on 2025-03-19 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.CharField(max_length=250)),
                ('short_description', models.CharField(max_length=250)),
                ('full_description', models.TextField()),
                ('platforms', models.CharField(choices=[('linkedin', 'linkedin'), ('headhunter', 'headhunter'), ('indeed', 'indeed')], max_length=50)),
                ('post_date', models.DateField()),
                ('status', models.CharField(choices=[('closed', 'closed'), ('active', 'active')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
