# Generated by Django 4.2 on 2025-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('closed', 'closed'), ('active', 'active')], default='active', max_length=50),
        ),
    ]
