# Generated by Django 4.2 on 2025-03-19 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_vacancy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='platforms',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='platforms',
            field=models.ManyToManyField(related_name='vacancies', to='common.platform'),
        ),
    ]
