# Generated by Django 4.2 on 2025-03-20 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_platform_remove_vacancy_platforms_vacancy_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('contact', models.EmailField(max_length=254)),
                ('apllied_from', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('reviewed', 'reviewed'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
